export default {
    trigger: '/',
    values: [
        {
            first_name: "张",
            last_name: "麻子",
            fullName: "张麻子",
            slug: "这个是我",
        },
        {
            first_name: "张",
            last_name: "三",
            fullName: "张三",
            slug: "我的哥哥",
        },
        {
            first_name: "诸葛",
            last_name: "四郎",
            fullName: "诸葛四郎",
            slug: "我的姨弟",
        },
        {
            first_name: "2张",
            last_name: "2麻子",
            fullName: "2张麻子",
            slug: "2这个是我",
        },
        {
            first_name: "3张",
            last_name: "3三",
            fullName: "3张三",
            slug: "3我的哥哥",
        },
        {
            first_name: "4诸葛",
            last_name: "4四郎",
            fullName: "4诸葛四郎",
            slug: "4我的姨弟",
        },
        {
            first_name: "5张",
            last_name: "5麻子",
            fullName: "5张麻子",
            slug: "5这个是我",
        },
        {
            first_name: "6张",
            last_name: "6三",
            fullName: "6张三",
            slug: "6我的哥哥",
        },
        {
            first_name: "7诸葛",
            last_name: "7四郎",
            fullName: "7诸葛四郎",
            slug: "7我的姨弟",
        },
        {
            first_name: "8张",
            last_name: "8麻子",
            fullName: "8张麻子",
            slug: "8这个是我",
        },
        {
            first_name: "9张",
            last_name: "9三",
            fullName: "9张三",
            slug: "9我的哥哥",
        },
        {
            first_name: "11诸葛",
            last_name: "11四郎",
            fullName: "11诸葛四郎",
            slug: "11我的姨弟",
        },
        {
            first_name: "12张",
            last_name: "12麻子",
            fullName: "12张麻子",
            slug: "12这个是我",
        },
        {
            first_name: "13张",
            last_name: "13三",
            fullName: "13张三",
            slug: "13我的哥哥",
        },
        {
            first_name: "14诸葛",
            last_name: "14四郎",
            fullName: "14诸葛四郎",
            slug: "14我的姨弟",
        },
        {
            first_name: "15张",
            last_name: "15麻子",
            fullName: "15张麻子",
            slug: "15这个是我",
        },
        {
            first_name: "16张",
            last_name: "16三",
            fullName: "16张三",
            slug: "16我的哥哥",
        },
        {
            first_name: "17诸葛",
            last_name: "17四郎",
            fullName: "17诸葛四郎",
            slug: "17我的姨弟",
        },
    ],
    lookup: (user) => user.first_name + user.last_name,
    fillAttr: "fullName",
    allowSpaces: true,
};
